### ISSUE TITLE
Custom JSON marshaller 

### ISSUE THREAD

**Issue by kluzzebass** [samber/slog-datadog#3]
The source attribute shows up like this in the Datadog interface:

`&{Function:main.main File:main.go Line:53}`

I would expect it to show up like in the `slog.JSONHandler`:

`{"function":"main.main","file":"main.go","line":53}`

(full paths redacted for brevity)

**Comment by kluzzebass** [comment]
Upon further study, this is does not just happen to source, but any complex type (like a struct) that would normally be marshalled into JSON.

**Comment by samber** [comment]
This is because we use slog.Source struct and no json tag have been set.

If you add `json:"foobar"` to your struct fields, this should be converted into a camel case style.

Currently, we use json.Marshal as serializer. I'm open to discussion about changing it.

- Hardcoded tag?
- Let the developer choose its tag?
- Use the first tag found in the struct, from a list of tags defined by developers?
- Default style when no tag is visible?

**Comment by kluzzebass** [comment]
Well, the way json.Marshal does it if there's no json tag is to camelCase the property name, and away it goes, and this is also how it's done in slog.JSONHandler. I can't really think of a reason to do it differently in this case.

https://cs.opensource.google/go/x/exp/+/1b970713:slog/json_handler.go

**Comment by kluzzebass** [comment]
Did you find a way to deal with this?

**Comment by samber** [comment]
Would a custom `json.Marshal` as Handler parameter would help ?

**Comment by kluzzebass** [comment]
Yeah, that would probably work.

**Comment by samber** [comment]
done

```go
logger := slog.New(slogdatadog.Option{
    Level: slog.LevelDebug,
    Client: apiClient,
    Context: ctx,
    Timeout: 5*time.Second,
    Hostname: host,
    Service: service,
    Marshal: jsoniter.NewEncoder(...).Froze().Marshal,
}.NewDatadogHandler())
```

**Comment by kluzzebass** [comment]
Hm, this doesn't look right. It seems that by the time the attribute map reaches the Marshaller-function, the value types are all strings, and all values have already been stringified.

**Comment by samber** [comment]
ok, feel free to suggest a better option

**Comment by addrummond** [comment]
I think the issue is here:

https://github.com/samber/slog-datadog/blob/62df9f573cf5ad832fa9dee0df554d5beaaf322c/converter.go#L65

I had the same problem as kluzzebass. Something like `slog.Info("Logged in", "user", user)` would convert the `user` struct to its Golang string representation and then set the `"user"` field of the log message to that string. As far as I can tell this behavior has nothing to do with the presence or absence of ```json:"..."``` tags.

I got things working the way I wanted by creating a custom `Converter` based on `converter.go`, but with the addition of the following `else if kind == slog.KindAny` branch:

```go
if attr.Key == "user" && kind == slog.KindGroup {
	attrToDatadogLog("usr.", v.Group(), log)
} else if kind == slog.KindGroup {
	attrToDatadogLog(base+k+".", v.Group(), log)
} else if kind == slog.KindAny {
	(*log)[base+k] = v.Any()
} else {
	(*log)[base+k] = slogcommon.ValueToString(v)
}
```

I then got the behaviour I was expecting (`user` is serialized to a JSON dictionary by `json.Marshal`).

I'm not sure if the current behavior is a bug or just different to what I was hoping for, but I thought I'd add this comment in case it sheds any light on the preceding discussion.
